apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

# 生成configmap
configMapGenerator:
  - name: mogu-picture-config
    files:
      - config.yaml

patchesStrategicMerge:
- deployment.yaml

namespace: default



