kind: pipeline
type: kubernetes
name: drone

platform:
  arch: amd64

trigger:
  branch:
    - master

steps:
  - name: build
    image: golang:1.19.2-alpine3.16
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    volumes:
      - name: cache
        path: /go
    commands:
      - go build -o mogu-picture main.go
  - name: publish
    image: registry.cn-guangzhou.aliyuncs.com/mogu-zh/drone-kaniko:latest
    settings:
      registry: registry.aliyuncs.com
      repo: mogu-zh/mogu-picture
      expand_repo: true
      auto_tag: true
      dockerfile: manifest/docker/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: install
    image: registry.aliyuncs.com/k8s-lzh/drone-cli:1.0.8
    settings:
      registry: registry.aliyuncs.com
      namespace: go-mogu
      chart_path: manifest/deploy/chart/mogu-picture
      chart_name: mogu-picture
#      tag: 1.0.0
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: cache
    host:
      path: /go
