package RedisConf

const (
	REQUEST_LIMIT                   = "REQUEST_LIMIT"
	SEGMENTATION                    = ":"
	WELL_NUMBER                     = "#"
	BLOG_CLICK                      = "BLOG_CLICK"
	IP_SOURCE                       = "IP_SOURCE"
	HOT_BLOG                        = "HOT_BLOG"
	NEW_BLOG                        = "NEW_BLOG"
	ADMIN_TOKEN                     = "ADMIN_TOKEN"
	SYSTEM_CONFIG                   = "SYSTEM_CONFIG"
	AVOID_REPEATABLE_COMMIT         = "AVOID_REPEATABLE_COMMIT"
	LOGIN_LIMIT                     = "LOGIN_LIMIT"
	USER_TOKEN                      = "USER_TOKEN"
	ACTIVATE_USER                   = "ACTIVATE_USER"
	LOGIN_TOKEN_KEY                 = "LOGIN_TOKEN_KEY"
	LOGIN_UUID_KEY                  = "LOGIN_UUID_KEY"
	USER_PUBLISH_SPAM_COMMENT_COUNT = "USER_PUBLISH_SPAM_COMMENT_COUNT"
	ADMIN_VISIT_MENU                = "ADMIN_VISIT_MENU"
	BLOG_PRAISE                     = "BLOG_PRAISE"
	ALL                             = "ALL"
	TAG_CLICK                       = "TAG_CLICK"
	SYSTEM_PARAMS                   = "SYSTEM_PARAMS"
	WEB_CONFIG                      = "WEB_CONFIG"
	DASHBOARD                       = "DASHBOARD"
	WEEK_VISIT                      = "WEEK_VISIT"
	BLOG_COUNT_BY_TAG               = "BLOG_COUNT_BY_TAG"
	BLOG_COUNT_BY_SORT              = "BLOG_COUNT_BY_SORT"
	BLOG_CONTRIBUTE_COUNT           = "BLOG_CONTRIBUTE_COUNT"
	BLOG_LINK                       = "BLOG_LINK"
	BLOG_TAG                        = "BLOG_TAG"
	USER_RECEIVE_COMMENT_COUNT      = "USER_RECEIVE_COMMENT_COUNT"
	LOGIN_TYPE                      = "LOGIN_TYPE"
	GITEE                           = "GITEE"
	GITHUB                          = "GITHUB"
	QQ                              = "QQ"
	PASSWORD                        = "PASSWORD"
	WECHAT                          = "WECHAT"
)
