// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/cloudStorage"
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/file"
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/fileSort"
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/localFileService"
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/networkDisk"
	_ "github.com/go-mogu/mogu-picture/internal/app/picture/logic/storage"
)
